lt-qcom/meta-qcom.sh: add missing packages
Install new required packages to fix the following error:
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  lz4c pzstd zstd

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
Change-Id: I366a0c5f9fea5f5ea99ea8ff0b45da84972f4c01