openembedded-lkft-linux-developer: Use Buster image
Recent changes in repo make it require a newer version of
Python 3, which was not available on the current Docker image
being used for this job.

With Buster, the more recent version of Python is there, thus
avoiding problems like the following:

  repo: warning: your Python 3 version is no longer supported; Please upgrade to Python 3.6+.
  Traceback (most recent call last):
    File "/srv/oe/.repo/repo/main.py", line 630, in <module>
      _Main(sys.argv[1:])
    File "/srv/oe/.repo/repo/main.py", line 604, in _Main
      result = run()
    File "/srv/oe/.repo/repo/main.py", line 597, in <lambda>
      run = lambda: repo._Run(name, gopts, argv) or 0
    File "/srv/oe/.repo/repo/main.py", line 205, in _Run
      git_trace2_event_log = EventLog()
    File "/srv/oe/.repo/repo/git_trace2_event_log.py", line 86, in __init__
      self._AddVersionEvent()
    File "/srv/oe/.repo/repo/git_trace2_event_log.py", line 96, in _AddVersionEvent
      version_event['exe'] = RepoSourceVersion()
    File "/srv/oe/.repo/repo/git_command.py", line 166, in RepoSourceVersion
      encoding='utf-8', env=env, check=False)
    File "/usr/lib/python3.5/subprocess.py", line 383, in run
      with Popen(*popenargs, **kwargs) as process:
  TypeError: __init__() got an unexpected keyword argument 'encoding'

Change-Id: I10f0a861f2e6ad1700e71d5f5f99a4e5cf86a3db
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>