rpb-openembedded/builders.sh: add missing packages
Install new required packages to fix the following error:
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  lz4c pzstd zstd

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
Change-Id: I35e1a4be1b9052d82f9d0f7acdc82a5830c4cffe